import { useCallback, useEffect, useMemo, useState } from "react";
import { Banknote, CalendarDays, CheckCircle2, CircleDollarSign, ClipboardList, CreditCard, Plus, Trash2, Users, X } from "lucide-react";
import toast from "react-hot-toast";
import {
  createPayrollAbsence, createPayrollHoliday, createPayrollPayment, createPayrollWage,
  endPayrollWage, getApiError, getMyPayroll, getPayrollAbsences, getPayrollHolidays,
  getPayrollPayments, getPayrollStaff, getPayrollWageSummary, getPayrollWages,
  updatePayrollWage, voidPayrollAbsence, voidPayrollHoliday, voidPayrollPayment,
} from "../services/api";
import { canAccess } from "../utils/rbac";
import TablePagination from "./TablePagination";

const PAGE_SIZE = 20;
const inputClass = "h-9 w-full rounded-lg border border-[#E2E8F0] bg-[#F8FAFC] px-3 text-xs text-[#334155] outline-none transition focus:border-[#0D8252] focus:bg-white";
const labelClass = "mb-1 block text-xs font-semibold text-[#334155]";

const emptyWage = { userId: "", rate: "", cycle: "MONTHLY", weeklyOff: [], effectiveFrom: "", note: "" };
const emptyAbsence = { userId: "", fromDate: "", toDate: "", kind: "FULL", reason: "SICK", note: "" };
const emptyHoliday = { name: "", fromDate: "", toDate: "", note: "" };
const emptyPayment = { userId: "", amount: "", method: "CASH", paidOn: "", note: "" };

function idOf(item) { return item?.id || item?._id || item?.uuid || item?.userId || ""; }
function dataOf(response) { const payload = response?.data || response || {}; return payload?.data ?? payload; }
function listOf(response) { const data = dataOf(response); return Array.isArray(data) ? data : data?.items || data?.results || data?.rows || []; }
function metaOf(response) { const payload = response?.data || response || {}; return payload?.meta || dataOf(response)?.meta || {}; }
function staffName(item) { return item?.staff?.name || item?.user?.name || item?.name || item?.staffName || item?.userName || "Staff member"; }
function staffEmail(item) { return item?.staff?.email || item?.user?.email || item?.email || ""; }
function staffId(item) { return item?.userId || idOf(item?.staff) || idOf(item?.user) || idOf(item); }
function localDate(value) { return String(value || "").match(/^\d{4}-\d{2}-\d{2}/)?.[0] || "-"; }
function money(value) { return new Intl.NumberFormat("en-IN", { style: "currency", currency: "INR", maximumFractionDigits: 2 }).format(Number(value || 0)); }
function status(value) {
  const active = String(value || "").toUpperCase();
  const good = ["ACTIVE", "RECORDED", "SETTLED"].includes(active);
  return <span className={`inline-flex rounded-full px-2 py-1 text-[10px] font-bold ${good ? "bg-[#0D8252]/10 text-[#0D8252]" : "bg-rose-50 text-rose-700"}`}>{active || "-"}</span>;
}

function Modal({ title, subtitle, icon = ClipboardList, children, onClose, footer }) {
  const ModalIcon = icon;
  useEffect(() => { const previous = document.body.style.overflow; document.body.style.overflow = "hidden"; return () => { document.body.style.overflow = previous; }; }, []);
  return <div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-900/35 p-4" onMouseDown={(event) => event.target === event.currentTarget && onClose()}>
    <section role="dialog" aria-modal="true" className="flex max-h-[90vh] w-full max-w-2xl flex-col overflow-hidden rounded-[18px] border border-[#E2E8F0] bg-white shadow-[0_30px_80px_rgba(15,23,42,0.18)]" onMouseDown={(event) => event.stopPropagation()}>
      <header className="flex items-start justify-between border-b border-[#E2E8F0] px-5 py-4"><div className="flex gap-3"><div className="flex h-10 w-10 items-center justify-center rounded-xl border border-[#CFEFDB] bg-[#EAFBF3] text-[#0D8252]"><ModalIcon size={18} /></div><div><h2 className="text-base font-bold text-[#0F172A]">{title}</h2>{subtitle && <p className="mt-0.5 text-xs text-[#64748B]">{subtitle}</p>}</div></div><button type="button" onClick={onClose} aria-label="Close modal" className="rounded-lg p-2 text-[#64748B] hover:bg-[#F1F5F9]"><X size={17} /></button></header>
      <div className="flex-1 overflow-y-auto px-5 py-4">{children}</div>
      <footer className="flex justify-end gap-3 border-t border-[#E2E8F0] px-5 py-4"><button type="button" onClick={onClose} className="rounded-lg border border-[#E2E8F0] px-4 py-2 text-xs font-semibold text-[#475569]">Cancel</button>{footer}</footer>
    </section>
  </div>;
}

function StaffSelect({ value, onChange, staff }) { return <select className={inputClass} value={value} onChange={(event) => onChange(event.target.value)} required><option value="">Select staff</option>{staff.map((person) => <option key={staffId(person)} value={staffId(person)}>{staffName(person)}{staffEmail(person) ? ` (${staffEmail(person)})` : ""}</option>)}</select>; }
function PageFooter({ meta, page, onPage }) { const pages = Math.max(1, Number(meta?.totalPages) || Math.ceil((Number(meta?.total) || 0) / PAGE_SIZE) || 1); return <div className="flex items-center justify-between border-t border-[#EEF2F4] px-4 py-3 text-xs text-[#64748B]"><span>{Number(meta?.total) || 0} records</span><TablePagination page={page} totalPages={pages} onPageChange={onPage} /></div>; }
function Empty({ message }) { return <div className="px-4 py-10 text-center text-sm text-[#94A3B8]">{message}</div>; }

export default function Payroll({ user }) {
  const canRead = canAccess(user, "payroll", "read");
  const canSelfRead = canAccess(user, "payroll", "self.read");
  const canCreate = canAccess(user, "payroll", "create");
  const canUpdate = canAccess(user, "payroll", "update");
  const canDelete = canAccess(user, "payroll", "delete");
  const canPay = canAccess(user, "payroll", "pay");
  const [tab, setTab] = useState(canRead ? "overview" : "mine");
  const [staff, setStaff] = useState([]); const [wages, setWages] = useState([]); const [payments, setPayments] = useState([]); const [absences, setAbsences] = useState([]); const [holidays, setHolidays] = useState([]);
  const [summaries, setSummaries] = useState({}); const [myPayroll, setMyPayroll] = useState(null); const [loading, setLoading] = useState(true); const [error, setError] = useState("");
  const [pages, setPages] = useState({ wages: 1, payments: 1, absences: 1, holidays: 1 }); const [metas, setMetas] = useState({}); const [filters, setFilters] = useState({ payments: { status: "" }, absences: { status: "" }, holidays: { status: "" } });
  const [modal, setModal] = useState(""); const [wageForm, setWageForm] = useState(emptyWage); const [absenceForm, setAbsenceForm] = useState(emptyAbsence); const [holidayForm, setHolidayForm] = useState(emptyHoliday); const [paymentForm, setPaymentForm] = useState(emptyPayment); const [selectedSummary, setSelectedSummary] = useState(null); const [busy, setBusy] = useState(false); const [voidTarget, setVoidTarget] = useState(null); const [voidReason, setVoidReason] = useState("");

  const request = useCallback(async (name, task) => { try { const response = await task(); return response; } catch (requestError) { const message = getApiError(requestError, `Unable to load ${name}`); setError(message); toast.error(message); return null; } }, []);
  const load = useCallback(async () => {
    setLoading(true); setError("");
    const tasks = canRead ? [getPayrollStaff({}, user?.token), getPayrollWages({ page: pages.wages, limit: PAGE_SIZE }, user?.token), getPayrollPayments({ page: pages.payments, limit: PAGE_SIZE, ...filters.payments }, user?.token), getPayrollAbsences({ page: pages.absences, limit: PAGE_SIZE, ...filters.absences }, user?.token), getPayrollHolidays({ page: pages.holidays, limit: PAGE_SIZE, ...filters.holidays }, user?.token)] : [getMyPayroll(user?.token)];
    try { const results = await Promise.all(tasks); if (canRead) { const [staffResponse, wageResponse, paymentResponse, absenceResponse, holidayResponse] = results; const staffList = listOf(staffResponse); setStaff(staffList); setWages(listOf(wageResponse)); setPayments(listOf(paymentResponse)); setAbsences(listOf(absenceResponse)); setHolidays(listOf(holidayResponse)); setMetas({ wages: metaOf(wageResponse), payments: metaOf(paymentResponse), absences: metaOf(absenceResponse), holidays: metaOf(holidayResponse) }); const summaryResults = await Promise.all(staffList.map(async (person) => [staffId(person), await getPayrollWageSummary(staffId(person), user?.token)])); setSummaries(Object.fromEntries(summaryResults.map(([id, response]) => [id, dataOf(response)]))); } else { setMyPayroll(dataOf(results[0])); } } catch (loadError) { const message = getApiError(loadError, "Unable to load payroll data"); setError(message); toast.error(message); } finally { setLoading(false); }
  }, [canRead, filters, pages, user?.token]);
  useEffect(() => { const timer = window.setTimeout(() => { void load(); }, 0); return () => window.clearTimeout(timer); }, [load]);
  const totals = useMemo(() => Object.values(summaries).reduce((result, summary) => ({ staff: result.staff + 1, accrued: result.accrued + Number(summary?.accrued || 0), paid: result.paid + Number(summary?.paid || 0), outstanding: result.outstanding + Math.max(0, Number(summary?.outstanding || 0)), credit: result.credit + Math.max(0, Number(summary?.credit || -Number(summary?.outstanding || 0))) }), { staff: 0, accrued: 0, paid: 0, outstanding: 0, credit: 0 }), [summaries]);
  const refreshAfterMutation = async (message) => { toast.success(message); setModal(""); setVoidTarget(null); setVoidReason(""); await load(); };
  const submit = async (event, action, message) => { event.preventDefault(); if (busy) return; setBusy(true); try { await action(); await refreshAfterMutation(message); } catch (submitError) { toast.error(getApiError(submitError)); } finally { setBusy(false); } };
  const openSummary = async (personId) => { const response = await request("staff payroll summary", () => getPayrollWageSummary(personId, user?.token)); if (response) { setSelectedSummary(dataOf(response)); setModal("summary"); } };
  const endWage = async (wage) => { if (!window.confirm("End this wage today? Historical payroll data will be retained.")) return; try { await endPayrollWage(idOf(wage), user?.token); await refreshAfterMutation("Wage ended"); } catch (actionError) { toast.error(getApiError(actionError)); } };
  const tabs = canRead ? [["overview", "Payroll Overview"], ["wages", "Staff Wages"], ["payments", "Payments"], ["absences", "Absences"], ["holidays", "Holidays"], ...(canSelfRead ? [["mine", "My Payroll"]] : [])] : [["mine", "My Payroll"]];
  if (!canRead && !canSelfRead) return <div className="rounded-lg border border-amber-200 bg-amber-50 p-5 text-sm text-amber-800">You do not have permission to view payroll.</div>;
  return <div className="space-y-5">
    <div className="flex flex-col gap-3 border-b border-[#E2E8F0] pb-4 sm:flex-row sm:items-end sm:justify-between"><div><h1 className="text-2xl font-bold text-[#0F172A]">Staff Payroll</h1><p className="mt-1 text-sm text-[#64748B]">Staff wages, accruals, absences, holidays, and salary payments.</p></div>{canRead && <button type="button" onClick={() => void load()} className="rounded-lg border border-[#E2E8F0] px-3 py-2 text-xs font-semibold text-[#475569]">Refresh</button>}</div>
    <div className="flex flex-wrap gap-2 border-b border-[#E2E8F0]">{tabs.map(([key, label]) => <button key={key} type="button" onClick={() => setTab(key)} className={`border-b-2 px-3 py-2 text-xs font-semibold ${tab === key ? "border-[#0D8252] text-[#0D8252]" : "border-transparent text-[#64748B] hover:text-[#334155]"}`}>{label}</button>)}</div>
    {error && <div className="rounded-lg border border-rose-200 bg-rose-50 px-4 py-3 text-sm text-rose-700">{error}</div>}
    {loading ? <div className="rounded-lg border border-[#E2E8F0] bg-white p-10 text-center text-sm text-[#64748B]">Loading payroll...</div> : <>
      {tab === "overview" && <><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-5">{[["Total Staff", totals.staff, Users], ["Total Accrued", money(totals.accrued), CircleDollarSign], ["Total Paid", money(totals.paid), CheckCircle2], ["Outstanding", money(totals.outstanding), Banknote], ["Credit", money(totals.credit), CreditCard]].map(([label, value, icon]) => { const CardIcon = icon; return <div key={label} className="rounded-lg border border-[#E2E8F0] bg-white p-4"><CardIcon size={18} className="text-[#0D8252]" /><p className="mt-3 text-xs font-semibold text-[#64748B]">{label}</p><p className="mt-1 text-xl font-bold text-[#0F172A]">{value}</p></div>; })}</div><section className="overflow-hidden rounded-lg border border-[#E2E8F0] bg-white"><div className="border-b border-[#EEF2F4] px-4 py-3 text-sm font-bold text-[#0F172A]">Staff balances</div><div className="overflow-x-auto"><table className="w-full min-w-[650px] text-left text-xs"><thead className="bg-[#F8FAFC] text-[#64748B]"><tr><th className="px-4 py-3">Staff</th><th className="px-4 py-3">Accrued</th><th className="px-4 py-3">Paid</th><th className="px-4 py-3">Result</th><th className="px-4 py-3" /></tr></thead><tbody>{staff.map((person) => { const summary = summaries[staffId(person)] || {}; const due = Number(summary.outstanding || 0); return <tr key={staffId(person)} className="border-t border-[#EEF2F4]"><td className="px-4 py-3"><p className="font-semibold text-[#334155]">{staffName(person)}</p><p className="text-[#94A3B8]">{staffEmail(person)}</p></td><td className="px-4 py-3">{money(summary.accrued)}</td><td className="px-4 py-3">{money(summary.paid)}</td><td className="px-4 py-3">{due < 0 || Number(summary.credit) > 0 ? <span className="font-semibold text-[#0D8252]">Credit {money(summary.credit || -due)}</span> : due > 0 ? <span className="font-semibold text-amber-700">Outstanding {money(due)}</span> : <span className="font-semibold text-[#0D8252]">Settled</span>}</td><td className="px-4 py-3"><button type="button" onClick={() => void openSummary(staffId(person))} className="text-xs font-semibold text-[#0D8252]">View summary</button></td></tr>; })}</tbody></table>{!staff.length && <Empty message="No payroll-eligible staff found." />}</div></section></>}
      {tab === "wages" && <PayrollTable title="Staff wages" action={canCreate && <button className="rounded-lg bg-[#0D8252] px-3 py-2 text-xs font-semibold text-white" onClick={() => { setWageForm(emptyWage); setModal("wage"); }}><Plus size={14} className="mr-1 inline" />Add Wage</button>}><table className="w-full min-w-[760px] text-left text-xs"><thead><tr><th>Staff</th><th>Rate</th><th>Cycle</th><th>Effective from</th><th>Effective to</th><th>Active</th><th /></tr></thead><tbody>{wages.map((wage) => <tr key={idOf(wage)}><td><p className="font-semibold">{staffName(wage)}</p><p className="text-[#94A3B8]">{staffEmail(wage)}</p></td><td>{money(wage.rate)}</td><td>{wage.cycle}</td><td>{localDate(wage.effectiveFrom)}</td><td>{localDate(wage.effectiveTo)}</td><td>{status(wage.isActive === false ? "INACTIVE" : "ACTIVE")}</td><td className="whitespace-nowrap">{canRead && <button className="mr-3 font-semibold text-[#0D8252]" onClick={() => void openSummary(staffId(wage))}>Summary</button>}{canUpdate && <button className="mr-3 font-semibold text-[#0D8252]" onClick={() => { setWageForm({ ...wage, effectiveTo: localDate(wage.effectiveTo) === "-" ? "" : localDate(wage.effectiveTo) }); setModal("edit-wage"); }}>Edit</button>}{canDelete && wage.isActive !== false && <button className="font-semibold text-rose-600" onClick={() => void endWage(wage)}>End Wage</button>}</td></tr>)}</tbody></table>{!wages.length && <Empty message="No wages created yet." />}<PageFooter meta={metas.wages} page={pages.wages} onPage={(page) => setPages((current) => ({ ...current, wages: page }))} /></PayrollTable>}
      {tab === "payments" && <PayrollTable title="Payroll payment history" action={<div className="flex gap-2"><select className="h-9 rounded-lg border border-[#E2E8F0] px-2 text-xs" value={filters.payments.status} onChange={(event) => setFilters((current) => ({ ...current, payments: { status: event.target.value } }))}><option value="">All statuses</option><option>RECORDED</option><option>VOID</option></select>{canPay && <button className="rounded-lg bg-[#0D8252] px-3 py-2 text-xs font-semibold text-white" onClick={() => { setPaymentForm(emptyPayment); setModal("payment"); }}><Plus size={14} className="mr-1 inline" />Record payment</button>}</div>}><table className="w-full min-w-[760px] text-left text-xs"><thead><tr><th>Staff</th><th>Amount</th><th>Method</th><th>Paid on</th><th>Status</th><th>Note</th><th /></tr></thead><tbody>{payments.map((payment) => <tr key={idOf(payment)}><td className="font-semibold">{staffName(payment)}</td><td>{money(payment.amount)}</td><td>{String(payment.method || "").replace("_", " ")}</td><td>{localDate(payment.paidOn)}</td><td>{status(payment.status)}</td><td className="max-w-48 truncate">{payment.note || "-"}</td><td>{canPay && String(payment.status).toUpperCase() !== "VOID" && <button className="font-semibold text-rose-600" onClick={() => { setVoidTarget({ type: "payment", item: payment }); setModal("void"); }}>Void</button>}</td></tr>)}</tbody></table>{!payments.length && <Empty message="No salary payments recorded." />}<PageFooter meta={metas.payments} page={pages.payments} onPage={(page) => setPages((current) => ({ ...current, payments: page }))} /></PayrollTable>}
      {tab === "absences" && <PayrollTable title="Staff absences" action={<div className="flex gap-2"><select className="h-9 rounded-lg border border-[#E2E8F0] px-2 text-xs" value={filters.absences.status} onChange={(event) => setFilters((current) => ({ ...current, absences: { status: event.target.value } }))}><option value="">All statuses</option><option>ACTIVE</option><option>VOID</option></select>{canCreate && <button className="rounded-lg bg-[#0D8252] px-3 py-2 text-xs font-semibold text-white" onClick={() => { setAbsenceForm(emptyAbsence); setModal("absence"); }}><Plus size={14} className="mr-1 inline" />Add absence</button>}</div>}><table className="w-full min-w-[700px] text-left text-xs"><thead><tr><th>Staff</th><th>From</th><th>To</th><th>Type</th><th>Reason</th><th>Status</th><th /></tr></thead><tbody>{absences.map((absence) => <tr key={idOf(absence)}><td className="font-semibold">{staffName(absence)}</td><td>{localDate(absence.fromDate)}</td><td>{localDate(absence.toDate || absence.fromDate)}</td><td>{absence.kind}</td><td>{absence.reason}</td><td>{status(absence.status || "ACTIVE")}</td><td>{canDelete && String(absence.status || "ACTIVE").toUpperCase() !== "VOID" && <button className="font-semibold text-rose-600" onClick={() => { setVoidTarget({ type: "absence", item: absence }); setModal("void"); }}>Void</button>}</td></tr>)}</tbody></table>{!absences.length && <Empty message="No absences recorded." />}<PageFooter meta={metas.absences} page={pages.absences} onPage={(page) => setPages((current) => ({ ...current, absences: page }))} /></PayrollTable>}
      {tab === "holidays" && <PayrollTable title="Gym holidays" action={<div className="flex gap-2"><select className="h-9 rounded-lg border border-[#E2E8F0] px-2 text-xs" value={filters.holidays.status} onChange={(event) => setFilters((current) => ({ ...current, holidays: { status: event.target.value } }))}><option value="">All statuses</option><option>ACTIVE</option><option>VOID</option></select>{canCreate && <button className="rounded-lg bg-[#0D8252] px-3 py-2 text-xs font-semibold text-white" onClick={() => { setHolidayForm(emptyHoliday); setModal("holiday"); }}><Plus size={14} className="mr-1 inline" />Add holiday</button>}</div>}><table className="w-full min-w-[650px] text-left text-xs"><thead><tr><th>Holiday</th><th>From</th><th>To</th><th>Note</th><th>Status</th><th /></tr></thead><tbody>{holidays.map((holiday) => <tr key={idOf(holiday)}><td className="font-semibold">{holiday.name}</td><td>{localDate(holiday.fromDate)}</td><td>{localDate(holiday.toDate || holiday.fromDate)}</td><td className="max-w-72 truncate">{holiday.note || "-"}</td><td>{status(holiday.status || "ACTIVE")}</td><td>{canDelete && String(holiday.status || "ACTIVE").toUpperCase() !== "VOID" && <button className="font-semibold text-rose-600" onClick={() => { setVoidTarget({ type: "holiday", item: holiday }); setModal("void"); }}>Void</button>}</td></tr>)}</tbody></table>{!holidays.length && <Empty message="No gym holidays recorded." />}<PageFooter meta={metas.holidays} page={pages.holidays} onPage={(page) => setPages((current) => ({ ...current, holidays: page }))} /></PayrollTable>}
      {tab === "mine" && <MyPayroll payroll={myPayroll} />}
    </>}
    {modal === "wage" && <Modal title="Add Wage" subtitle="Create a versioned staff wage." icon={Banknote} onClose={() => setModal("")} footer={<button form="payroll-wage" disabled={busy} className="rounded-lg bg-[#0D8252] px-4 py-2 text-xs font-semibold text-white">{busy ? "Saving..." : "Save Wage"}</button>}><form id="payroll-wage" className="grid gap-3 sm:grid-cols-2" onSubmit={(event) => submit(event, () => createPayrollWage({ ...wageForm, rate: Number(wageForm.rate), weeklyOff: wageForm.cycle === "DAILY" ? wageForm.weeklyOff : [] }, user?.token), "Wage created")}><Field label="Staff"><StaffSelect value={wageForm.userId} onChange={(userId) => setWageForm((form) => ({ ...form, userId }))} staff={staff} /></Field><Field label="Rate"><input required min="0" type="number" className={inputClass} value={wageForm.rate} onChange={(event) => setWageForm((form) => ({ ...form, rate: event.target.value }))} /></Field><Field label="Cycle"><select className={inputClass} value={wageForm.cycle} onChange={(event) => setWageForm((form) => ({ ...form, cycle: event.target.value }))}><option>MONTHLY</option><option>DAILY</option></select></Field><Field label="Effective From"><input required type="date" className={inputClass} value={wageForm.effectiveFrom} onChange={(event) => setWageForm((form) => ({ ...form, effectiveFrom: event.target.value }))} /></Field>{wageForm.cycle === "DAILY" && <div className="sm:col-span-2"><p className={labelClass}>Weekly Off</p><div className="flex flex-wrap gap-3">{["SUNDAY","MONDAY","TUESDAY","WEDNESDAY","THURSDAY","FRIDAY","SATURDAY"].map((day) => <label key={day} className="inline-flex items-center gap-1 text-xs text-[#475569]"><input type="checkbox" checked={wageForm.weeklyOff.includes(day)} onChange={(event) => setWageForm((form) => ({ ...form, weeklyOff: event.target.checked ? [...form.weeklyOff, day] : form.weeklyOff.filter((value) => value !== day) }))} className="accent-[#0D8252]" />{day.slice(0, 3)}</label>)}</div></div>}<Field label="Note" wide><textarea className={`${inputClass} h-20 py-2`} value={wageForm.note} onChange={(event) => setWageForm((form) => ({ ...form, note: event.target.value }))} /></Field></form></Modal>}
    {modal === "edit-wage" && <Modal title="Edit Wage" subtitle="Rate, cycle, weekly off, and effective-from are immutable." onClose={() => setModal("")} footer={<button form="edit-payroll-wage" disabled={busy} className="rounded-lg bg-[#0D8252] px-4 py-2 text-xs font-semibold text-white">{busy ? "Saving..." : "Save changes"}</button>}><form id="edit-payroll-wage" className="grid gap-3" onSubmit={(event) => submit(event, () => updatePayrollWage(idOf(wageForm), { effectiveTo: wageForm.effectiveTo || undefined, isActive: wageForm.isActive !== false, note: wageForm.note || undefined }, user?.token), "Wage updated")}><Field label="Effective To"><input type="date" className={inputClass} value={wageForm.effectiveTo || ""} onChange={(event) => setWageForm((form) => ({ ...form, effectiveTo: event.target.value }))} /></Field><Field label="Note"><textarea className={`${inputClass} h-20 py-2`} value={wageForm.note || ""} onChange={(event) => setWageForm((form) => ({ ...form, note: event.target.value }))} /></Field><label className="inline-flex items-center gap-2 text-xs font-semibold text-[#334155]"><input type="checkbox" checked={wageForm.isActive !== false} onChange={(event) => setWageForm((form) => ({ ...form, isActive: event.target.checked }))} className="accent-[#0D8252]" />Active</label>{wageForm.isActive === false && !wageForm.effectiveTo && <p className="text-xs text-rose-600">An effective end date is required when deactivating a wage.</p>}</form></Modal>}
    {modal === "absence" && <Modal title="Add Absence" subtitle="Backend validation protects against payroll clawbacks." icon={CalendarDays} onClose={() => setModal("")} footer={<button form="payroll-absence" disabled={busy} className="rounded-lg bg-[#0D8252] px-4 py-2 text-xs font-semibold text-white">{busy ? "Saving..." : "Save absence"}</button>}><form id="payroll-absence" className="grid gap-3 sm:grid-cols-2" onSubmit={(event) => submit(event, () => createPayrollAbsence({ ...absenceForm, toDate: absenceForm.toDate || undefined }, user?.token), "Absence created")}><Field label="Staff"><StaffSelect value={absenceForm.userId} onChange={(userId) => setAbsenceForm((form) => ({ ...form, userId }))} staff={staff} /></Field><Field label="Absence Type"><select className={inputClass} value={absenceForm.kind} onChange={(event) => setAbsenceForm((form) => ({ ...form, kind: event.target.value }))}><option>FULL</option><option>HALF</option></select></Field><Field label="From Date"><input required type="date" className={inputClass} value={absenceForm.fromDate} onChange={(event) => setAbsenceForm((form) => ({ ...form, fromDate: event.target.value }))} /></Field><Field label="To Date"><input type="date" className={inputClass} value={absenceForm.toDate} onChange={(event) => setAbsenceForm((form) => ({ ...form, toDate: event.target.value }))} /></Field><Field label="Reason"><select className={inputClass} value={absenceForm.reason} onChange={(event) => setAbsenceForm((form) => ({ ...form, reason: event.target.value }))}>{["SICK","CASUAL","UNPAID","FESTIVAL","PERSONAL","OTHER"].map((reason) => <option key={reason}>{reason}</option>)}</select></Field><Field label="Note" wide><textarea className={`${inputClass} h-20 py-2`} value={absenceForm.note} onChange={(event) => setAbsenceForm((form) => ({ ...form, note: event.target.value }))} /></Field></form></Modal>}
    {modal === "holiday" && <Modal title="Add Holiday" subtitle="A holiday applies across staff wages." icon={CalendarDays} onClose={() => setModal("")} footer={<button form="payroll-holiday" disabled={busy} className="rounded-lg bg-[#0D8252] px-4 py-2 text-xs font-semibold text-white">{busy ? "Saving..." : "Save holiday"}</button>}><form id="payroll-holiday" className="grid gap-3 sm:grid-cols-2" onSubmit={(event) => submit(event, () => createPayrollHoliday({ ...holidayForm, toDate: holidayForm.toDate || holidayForm.fromDate }, user?.token), "Holiday created")}><Field label="Holiday Name"><input required className={inputClass} value={holidayForm.name} onChange={(event) => setHolidayForm((form) => ({ ...form, name: event.target.value }))} /></Field><div /><Field label="From Date"><input required type="date" className={inputClass} value={holidayForm.fromDate} onChange={(event) => setHolidayForm((form) => ({ ...form, fromDate: event.target.value }))} /></Field><Field label="To Date"><input type="date" className={inputClass} value={holidayForm.toDate} onChange={(event) => setHolidayForm((form) => ({ ...form, toDate: event.target.value }))} /></Field><Field label="Note" wide><textarea className={`${inputClass} h-20 py-2`} value={holidayForm.note} onChange={(event) => setHolidayForm((form) => ({ ...form, note: event.target.value }))} /></Field></form></Modal>}
    {modal === "payment" && <Modal title="Record Salary Payment" subtitle="Payments may exceed accrued salary; the remainder becomes credit." icon={CreditCard} onClose={() => setModal("")} footer={<button form="payroll-payment" disabled={busy} className="rounded-lg bg-[#0D8252] px-4 py-2 text-xs font-semibold text-white">{busy ? "Saving..." : "Record payment"}</button>}><form id="payroll-payment" className="grid gap-3 sm:grid-cols-2" onSubmit={(event) => submit(event, () => createPayrollPayment({ ...paymentForm, amount: Number(paymentForm.amount) }, user?.token), "Salary payment recorded")}><Field label="Staff"><StaffSelect value={paymentForm.userId} onChange={(userId) => setPaymentForm((form) => ({ ...form, userId }))} staff={staff} /></Field><Field label="Amount"><input required min="0.01" step="0.01" type="number" className={inputClass} value={paymentForm.amount} onChange={(event) => setPaymentForm((form) => ({ ...form, amount: event.target.value }))} /></Field><Field label="Method"><select className={inputClass} value={paymentForm.method} onChange={(event) => setPaymentForm((form) => ({ ...form, method: event.target.value }))}><option>CASH</option><option>BANK_TRANSFER</option></select></Field><Field label="Paid On"><input required max={new Date().toISOString().slice(0, 10)} type="date" className={inputClass} value={paymentForm.paidOn} onChange={(event) => setPaymentForm((form) => ({ ...form, paidOn: event.target.value }))} /></Field><Field label="Note" wide><textarea className={`${inputClass} h-20 py-2`} value={paymentForm.note} onChange={(event) => setPaymentForm((form) => ({ ...form, note: event.target.value }))} /></Field></form></Modal>}
    {modal === "void" && <Modal title={`Void ${voidTarget?.type || "record"}`} subtitle="This action is recorded and cannot be undone." icon={Trash2} onClose={() => setModal("")} footer={<button disabled={busy || (voidTarget?.type === "payment" && !voidReason.trim())} onClick={() => void submit({ preventDefault() {} }, () => voidTarget.type === "payment" ? voidPayrollPayment(idOf(voidTarget.item), { voidReason }, user?.token) : voidTarget.type === "absence" ? voidPayrollAbsence(idOf(voidTarget.item), user?.token) : voidPayrollHoliday(idOf(voidTarget.item), user?.token), `${voidTarget?.type || "Record"} voided`)} className="rounded-lg bg-rose-600 px-4 py-2 text-xs font-semibold text-white disabled:opacity-50">{busy ? "Voiding..." : "Confirm void"}</button>}>{voidTarget?.type === "payment" && <Field label="Void reason"><textarea required className={`${inputClass} h-20 py-2`} value={voidReason} onChange={(event) => setVoidReason(event.target.value)} /></Field>}</Modal>}
    {modal === "summary" && <Modal title="Staff Payroll Summary" subtitle={`${selectedSummary?.staff?.name || "Staff member"}${selectedSummary?.staff?.email ? ` - ${selectedSummary.staff.email}` : ""}`} icon={CircleDollarSign} onClose={() => setModal("")}><Summary summary={selectedSummary} /></Modal>}
  </div>;
}

function PayrollTable({ title, action, children }) { return <section className="overflow-hidden rounded-lg border border-[#E2E8F0] bg-white"><div className="flex flex-wrap items-center justify-between gap-3 border-b border-[#EEF2F4] px-4 py-3"><h2 className="text-sm font-bold text-[#0F172A]">{title}</h2>{action}</div><div className="overflow-x-auto [&_th]:bg-[#F8FAFC] [&_th]:px-4 [&_th]:py-3 [&_th]:font-semibold [&_th]:text-[#64748B] [&_td]:border-t [&_td]:border-[#EEF2F4] [&_td]:px-4 [&_td]:py-3">{children}</div></section>; }
function Field({ label, children, wide = false }) { return <label className={wide ? "sm:col-span-2" : ""}><span className={labelClass}>{label}</span>{children}</label>; }
function Summary({ summary }) { if (!summary) return <Empty message="No payroll summary available." />; const due = Number(summary.outstanding || 0); return <div className="space-y-4 text-sm"><div className="grid gap-3 sm:grid-cols-2">{[["Current wage", summary.currentWage ? `${money(summary.currentWage.rate)} / ${summary.currentWage.cycle}` : "No active wage"], ["Accrued", money(summary.accrued)], ["Paid", money(summary.paid)], [due < 0 || Number(summary.credit) > 0 ? "Credit" : "Outstanding", money(summary.credit || Math.max(0, due))], ["Days accrued", summary.daysAccrued ?? "-"], ["Period", `${localDate(summary.startsOn)} to ${localDate(summary.through)}`]].map(([label, value]) => <div key={label} className="rounded-lg bg-[#F8FAFC] p-3"><p className="text-xs font-semibold text-[#64748B]">{label}</p><p className="mt-1 font-bold text-[#0F172A]">{value}</p></div>)}</div><div><h3 className="text-sm font-bold text-[#0F172A]">Unpaid days</h3>{summary.unpaidDays?.length ? <div className="mt-2 space-y-2">{summary.unpaidDays.map((day, index) => <div key={`${day.date}-${index}`} className="flex justify-between rounded-lg border border-[#E2E8F0] px-3 py-2 text-xs"><span>{localDate(day.date)}</span><strong>{money(day.amount)}</strong></div>)}</div> : <p className="mt-2 text-xs text-[#94A3B8]">No unpaid days.</p>}</div></div>; }
function MyPayroll({ payroll }) { if (!payroll) return <Empty message="No payroll record available." />; return <section className="space-y-4"><Summary summary={payroll} /><div className="overflow-hidden rounded-lg border border-[#E2E8F0] bg-white"><div className="border-b border-[#EEF2F4] px-4 py-3 text-sm font-bold text-[#0F172A]">Payment history</div>{payroll.payments?.length ? <div className="overflow-x-auto"><table className="w-full min-w-[520px] text-left text-xs"><thead className="bg-[#F8FAFC]"><tr><th className="px-4 py-3">Amount</th><th className="px-4 py-3">Method</th><th className="px-4 py-3">Paid On</th><th className="px-4 py-3">Status</th></tr></thead><tbody>{payroll.payments.map((payment) => <tr key={idOf(payment)} className="border-t border-[#EEF2F4]"><td className="px-4 py-3">{money(payment.amount)}</td><td className="px-4 py-3">{String(payment.method || "").replace("_", " ")}</td><td className="px-4 py-3">{localDate(payment.paidOn)}</td><td className="px-4 py-3">{status(payment.status)}</td></tr>)}</tbody></table></div> : <Empty message="No salary payments recorded." />}</div></section>; }
